version: '3.8'

services:
  log_analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log_analyzer-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: logs_db
    volumes:
      - postgres-date:/var/lib/postgres/data
    networks:
      - app-network

volumes:
  postgres-date:

networks:
  app-network:
    driver: bridge




